### ISSUE TITLE
Don’t work login

### ISSUE THREAD

**Issue by grizunalexey** [tomasbedrich/home-assistant-hikconnect#50]
Authentication failure. May be a wrong username/password combination or CAPTCHA. Try logging in using official Hik-Connect application.

**Comment by zzz676** [comment]
+
Login not work

**Comment by sp3cialck** [comment]
Here the same, isn't working anymore, same error!

**Comment by tomasbedrich** [comment]
Works for me. Please provide a debug output.

**Comment by Waitingforthesun** [comment]
> Works for me. Please provide a debug output.

Hi, issue persists:
`2024-12-17 21:59:27.516 ERROR (MainThread) [custom_components.hikconnect.config_flow] Hik-Connect login failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 97, in login
    session_id = res_json["loginSession"]["sessionId"]
                 ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'loginSession'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/hikconnect/config_flow.py", line 55, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/hikconnect/config_flow.py", line 42, in validate_input
    await api.login(data["username"], data["password"])
  File "/usr/local/lib/python3.13/site-packages/hikconnect/api.py", line 99, in login
    raise LoginError("Unable to parse session_id from response.") from e
hikconnect.exceptions.LoginError: Unable to parse session_id from response.`
